export const NOTIFICATION_TYPES = {
  NOTIFICATION_LOADING: 'NOTIFICATION_LOADING',
  GET_NOTIFICATION: 'GET_NOTIFICATION',
  CREATE_NOTIFICATION: 'CREATE_NOTIFICATION',
  READ_NOTIFICATION: 'READ_NOTIFICATION',
  DELETE_NOTIFICATION: 'DELETE_NOTIFICATION'
};