export const PROFILE_TYPES = {
  LOADING: 'PROFILE_LOADING',
  GET_USER_PROFILE: 'GET_USER_PROFILE',
  FOLLOW: 'FOLLOW',
  UNFOLLOW: 'UNFOLLOW',
  GET_POST: 'GET_PROFILE_POST',
  EDIT_POST: 'EDIT_PROFILE_POST'
};